### ISSUE TITLE
Incorrect definition of SpacingMark used

### ISSUE THREAD

**Issue by syvb** [unicode-rs/unicode-segmentation#108]
[UAX #29](https://www.unicode.org/reports/tr29/tr29-39.html#SpacingMark) defines `SpacingMark` as:

> Grapheme_Cluster_Break ≠ Extend, _and_
General_Category = Spacing_Mark, _or_
_any of the following (which have General_Category = Other_Letter):_
U+0E33 ( ำ ) THAI CHARACTER SARA AM
U+0EB3 ( ຳ ) LAO VOWEL SIGN AM
>
> Exceptions: The following (which have General_Category = Spacing_Mark and would otherwise be included) are specifically excluded:
> [24 exception characters]

In [this crate's implementation of rule GB9a](https://github.com/unicode-rs/unicode-segmentation/blob/9d79ee2acbe159d3557918ca1a5290995eef9a7e/src/grapheme.rs#L269), only the "General_Category = Spacing_Mark" part is checked. This crate doesn't check that Grapheme_Cluster_Break ≠ Extend or implement any of the 24 exclusions or 2 inclusions. The impact of this is very minor though, since it only affects a small set of characters, and only in extended mode.

_(originally noted in #107)_

**Comment by Jules-Bertholet** [comment]
There's no issue here. `GC`  in the code does not stand for "General Category", but for `GraphemeCat`. The categories are read from https://www.unicode.org/Public/UNIDATA/auxiliary/GraphemeBreakProperty.txt, which contains the right values. This can be closed
