### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by giarc3** [unicode-rs/unicode-segmentation#109]
It looks like the Changelog at the bottom of the README has not been updated since `1.7.1`. Would it be possible to update this with the latest information?
Additionally, putting this information into a CHANGELOG.md at the root would make it easier for something like Dependabot to find new release information.
Thank you very much.

**Comment by Manishearth** [comment]
Happy to accept a changelog PR (and happy to answer questions about changes for someone crafting one), but I don't have the time to do this right now. It's a good idea, though!

**Comment by nicolasmendoza** [comment]
@Manishearth  Changelogs updated: https://github.com/unicode-rs/unicode-segmentation/pull/127
