### ISSUE TITLE
trivial?  crates.io README has broken example...

### ISSUE THREAD

**Issue by asah** [unicode-rs/unicode-segmentation#122]
README.md is correct but https://crates.io/crates/unicode-segmentation still shows:
```
    let b: &[_] = &["The", " ", "quick", " ", "(", "\"", "brown", "\"", ")", " ", " ", "fox"];
```
which produces an error when executed.

**Comment by syvb** [comment]
This issue can be closed now - there was a release and the example in the README on crates.io now passes.
