### ISSUE TITLE
Fix failing Devanagari क tests

### ISSUE THREAD

**Issue by syvb** [unicode-rs/unicode-segmentation#125]
Currently we skip these tests from the Unicode test suite (see #124):
https://github.com/unicode-rs/unicode-segmentation/blob/6191f8e287a5cd534af54974952957a6e7bdf6a1/src/test.rs#L53

We should fix whatever issue is causing these to fail.

**Comment by nicolasmendoza** [comment]
Hi @syvb

I'd like to work on this Issue #125, Is it still open for contribution? If so, may I claim it?

**Comment by syvb** [comment]
@nicolasmendoza I'm not working on this myself, you can claim this if you want. (also: to be clear, I'm not a maintainer of this crate)
