### ISSUE TITLE
Bug/Implement: chinese words not detected, and the Debug trait

### ISSUE THREAD

**Issue by mabbamOG** [unicode-rs/unicode-segmentation#33]
Hello,
i stumbled upon your package when adding support to my program for chinese text.
Namely, i need to find the words in that text.
Currently i use `split_whitespace()` and then remove special characters (such as commas) from the words.
But split_whitespace does not work on the following:
```
我的 "my/I"
猫 "cat"
很大 "very big"

我的猫很大 "my cat is very big" <--- chinese not separated by spaces!
```

But `graphemes()` is capable of detecting characters, not words (我的 is split into 2, yet it's a single word) and `unicode_words()` seems to do the same.

`Unicode_words()` seems to be a perfect match for me (since it can handle removing special characters) but it is not detecting chinese word boundaries right.

Also, being able to
 ``` rust 
println!("{:?}", UnicodeSegmentation::unicode_words("我的猫很大"));
```
would be ideal when testing this kinda stuff, thanks!

**Comment by mabbamOG** [comment]
implementing the Join trait (even though it's nightly) would also be a nice future feature

**Comment by Manishearth** [comment]
So, this crate implements [UAX 29](http://www.unicode.org/reports/tr29/), which is a specific algorithm.

With respect to this, it mentions,

> As with the other default specifications, implementations may override (tailor) the results to meet the requirements of different environments or particular languages. For some languages, it may also be necessary to have different tailored word break rules for selection versus Whole Word Search.

> In particular, the characters with the Line_Break property values of Contingent_Break (CB), Complex_Context (SA/Southeast Asian), and Unknown (XX) are assigned Word_Break property values based on criteria outside of the scope of this annex. That means that satisfactory treatment of languages like Chinese or Thai requires special handling.



Furthermore, chinese is fundamentally not a language that can algorithmically handle line breaks (unlike Thai!). Things which are one word in some contexts (e.g. 大, in your example), can be multiple in others. 多少, and 小心 are good examples of this. Besides, I don't think there are very clear concepts of words here (I could be wrong). Even "我的" can be viewed of being two words, the word 我 for "I" and the particle 的. Google Translate segments your sentence this way, for example, see https://translate.google.com/#en/zh-CN/my%20cat%20is%20big and the pinyin below it, unlike https://translate.google.com/#en/zh-CN/my%20cat%20is%20too%20big where 大了 is shown as one word in the pinyin. You basically need to program a dictionary and probably a whole bunch of contextual stuff, which is far outside the scope of this project. ICU handles this with a dictionary, I think.

**Comment by mabbamOG** [comment]
I see, thanks for the helpful explanation!
