### ISSUE TITLE
Segmentation of combined emojis

### ISSUE THREAD

**Issue by RazrFalcon** [unicode-rs/unicode-segmentation#42]
```rust
for c in UnicodeSegmentation::graphemes("🏳️‍🌈", true) {
    println!("{}", c);
}
```

Outputs:
```
🏳️‍
🌈
```
🏳️‍
🌈

But should output:
```
🏳️‍🌈
```
🏳️‍🌈

Another example: `👮‍♀`.

Is it `UnicodeSegmentation` bug or am I doing this wrong? For my current task this should be a single "character".

**Comment by Manishearth** [comment]
We're operating off an old unicode version (9) where that's not in the tables.

https://www.unicode.org/Public/9.0.0/ucd/auxiliary/GraphemeBreakProperty.txt

Filed https://github.com/unicode-rs/unicode-segmentation/issues/43

That may take a while to fix, but it may be worth updating to Unicode 10 in the interim (which is an easier update than 10 to 11), and will also fix your issue.
