### ISSUE TITLE
Update to Unicode 11

### ISSUE THREAD

**Issue by Manishearth** [unicode-rs/unicode-segmentation#43]
Unicode 11 comes out in June, and we should update to it.

There are a bunch of changes to the grapheme and word stuff involved here. Most of the complex emoji rules have been replaced with things using `\p{Extended_Pictographic}`, which is not a disjoint grapheme category, rather it is an additional property. This crate may require some refactoring.

We may want to update to Unicode 10 before that; that should be a straightforward regen of the tables IIRC.

**Comment by rth** [comment]
> We may want to update to Unicode 10 before that; that should be a straightforward regen of the tables IIRC.

PR proposed in #56

**Comment by Manishearth** [comment]
Some more background on the emoji simplifications in 11: https://unicode.org/mail-arch/unicode-ml/y2018-m01/0000.html,  http://www.unicode.org/review/pri355/

**Comment by wezm** [comment]
Can this be closed now that #72 is merged?
