### ISSUE TITLE
Arabic text

### ISSUE THREAD

**Issue by fasihrana** [unicode-rs/unicode-segmentation#50]
Is there something that allows converting a string of individual Arabic characters to the proper joined form of Arabic text?

For example my name written in individual letters is:
`ف ص ی ح`
while the joined form is (if you view this in any modern browser):
`فصیح`

This is probably not raised in the right repository, but I could not see any others which would be suitable.

**Comment by Manishearth** [comment]
This crate isn't it.

In the example you gave it's just removing spaces. There are Arabic letters that do not combine and converting from those is trickier.

**Comment by Manishearth** [comment]
This is a matter of getting your terminal to render Arabic correctly, Rust cannot help with that.

If you're talking about a Rust-basee UI system that can render Arabic correctly you'd want to use harfbuzz, but that bug belongs on whatever UI crate you're using.
