### ISSUE TITLE
Remove `extern crate` from examples (or add comment about Rust edition)

### ISSUE THREAD

**Issue by HarrisonMc555** [unicode-rs/unicode-segmentation#58]
**Proposal:** I think we should remove the `extern crate` declaration in the README, or at least put a comment above it noting that it is only necessary if you're on the Rust 2015 edition.

**Background:** I am a mentor on [exercism.io](https://exercism.io), and our first "real" exercise (after "Hello, World") is the "Reverse String" exercise. We have a "bonus" test case where a string contains "characters" that are multiple code points. Most students rightly find this crate and use it to extract the graphemes from a string and reverse those. However, many of them leave in the `extern crate` declaration, even though essentially all of them are using Rust 2018 and don't need it.

**Comment by Manishearth** [comment]
I'm all for just removing it without a comment.

**Comment by Manishearth** [comment]
Fixed. Crate itself is on 2015 edition, but I made a PR to fix that: https://github.com/unicode-rs/unicode-segmentation/pull/59

**Comment by Manishearth** [comment]
Hm, so there's a problem, we run `rustdoc --test` on the readme, but you need cargo to orchestrate crate imports for stuff like this.

**Comment by HarrisonMc555** [comment]
Hmm...I was going to say you could use the "doc comment" thing where you start a line with `#` and it's not displayed in the documentation, but that wouldn't work on a README. Bummer. I'm guessing you looked [here](https://github.com/rust-lang/rust/issues/58875) and determined it wasn't possible?

Are you planning on just upgrading to Rust 2018 and not supporting Rust 2015 (via #59)? Let me know if there's anything I can do to help.

**Comment by Manishearth** [comment]
Yeah I know how rustdoc works around this, it's not possible and it's not
likely that that will change, edition 2018 requires --extern flags.

We could do some shell scripting to make it work
