### ISSUE TITLE
Wrong graphemes length of 🤦🏼‍♂️ emoji

### ISSUE THREAD

**Issue by weihanglo** [unicode-rs/unicode-segmentation#62]
I read [this post](https://hsivonen.fi/string-length/) and found that segmentation over this emoji is wrong due to new rule of ZERO WIDTH JOINER. Concerning I have only little knowledge about Unicode, is there anything I can help?

## Reproducible Demo

[Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a21238e7f0ec54842acf156225ae1ce6)

```rust
use unicode_segmentation::UnicodeSegmentation;

fn main() {
	let s = "🤦🏼‍♂️";
	println!("{}", s.graphemes(true).count());
	println!("{}", s.chars().count());
	println!("{}", s.encode_utf16().count());
	println!("{}", s.len());
}

// 2 <---- should be 1
// 5
// 7
// 17

```

**Comment by Manishearth** [comment]
This crate needs an update. https://github.com/unicode-rs/unicode-segmentation/issues/43
