### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [unicode-rs/unicode-segmentation#84]
`unicode-segmentation` does not seem to use unsafe code, which is very good :)
It seems to have the rule: `#![deny(missing_docs, unsafe_code)]`
https://github.com/unicode-rs/unicode-segmentation/blob/ec65d220e652dbfea9eca349248d5782e4addf91/src/lib.rs#L52

I would suggest changing this to:
```rust
#![forbid(unsafe_code)]
#![deny(missing_docs)]
```
in https://github.com/unicode-rs/unicode-segmentation/blob/master/src/lib.rs
This is a bit stricter and will make the package green in 
https://github.com/rust-secure-code/cargo-geiger

**Comment by Manishearth** [comment]
I'm generally not a fan of unnecessary forbid(unsafe)s for similar reasons as David in https://github.com/alexcrichton/proc-macro2/pull/261#pullrequestreview-497017967
