### ISSUE TITLE
Typo in `/src/graphmeme.rs`

### ISSUE THREAD

**Issue by gastrodon** [unicode-rs/unicode-segmentation#85]
https://github.com/unicode-rs/unicode-segmentation/blob/ec65d220e652dbfea9eca349248d5782e4addf91/src/grapheme.rs#L226

possible typo? Unless iff is something that I'm not aware of, if so sorry!

**Comment by mbrubeck** [comment]
In mathematic and formal logic, [iff](https://en.wikipedia.org/wiki/If_and_only_if) means “if and only if.”

**Comment by gastrodon** [comment]
I was unaware of that, thanks
