### ISSUE TITLE
Missing changelog for 1.7

### ISSUE THREAD

**Issue by dhardy** [unicode-rs/unicode-segmentation#88]
Could you please add this?

**Comment by dhardy** [comment]
The [docs](https://github.com/unicode-rs/unicode-segmentation/blob/master/src/lib.rs#L49) also need an update.

**Comment by chrissimpkins** [comment]
I don't believe that there has been a release of the Unicode 13 changes.  I submitted the PR with those updates.  If there is anything that I can do to help prep a release, please let me know.

**Comment by Manishearth** [comment]
Ah, the publication commit wasn't pushed. I anyway did a new commit for 1.7.1 with the doc changes https://github.com/unicode-rs/unicode-segmentation/commit/3b75ee19b3c0ddacaeec03be688a7b8766833728
