### ISSUE TITLE
Please add a `Debug` implementation for `Graphemes` and so on

### ISSUE THREAD

**Issue by ChaiTRex** [unicode-rs/unicode-segmentation#95]
The `std::str::Chars` iterator has a nice `Debug` output:

```rust
fn main() {
    let mut chars = "abc".chars();
    println!("{:?}", chars);
    chars.next();
    println!("{:?}", chars);
}
```

produces:

    Chars(['a', 'b', 'c'])
    Chars(['b', 'c'])

---

It would be nice to see `unicode_segmentation::Graphemes` and so forth implement a nice `Debug` output to display what they're going to be producing in the future.

**Comment by timClicks** [comment]
One of the complications with `Debug` is that, by default, it exposes lots of internals. `Graphenes` holds a lot of state, and so its `Debug` output is quite ugly.

I've submitted #98 anyway. Let's see what the maintainers think

**Comment by Manishearth** [comment]
Yeah, we could improve the debug impl but for now this one is fine
